//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZoneTestProjects.Functional.Reports.Settings.Interface.SystemAdmin.Institution {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class InstitutionValidation : global::System.Configuration.ApplicationSettingsBase {
        
        private static InstitutionValidation defaultInstance = ((InstitutionValidation)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InstitutionValidation())));
        
        public static InstitutionValidation Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Institutions_wrapper > div.dt-toolbar-footer")]
        public string InstitutionFooter {
            get {
                return ((string)(this["InstitutionFooter"]));
            }
            set {
                this["InstitutionFooter"] = value;
            }
        }
    }
}
