//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZoneTestProjects.Functional.Reports.Settings.Interface.SystemAdmin.Institution {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class InstitutionElements : global::System.Configuration.ApplicationSettingsBase {
        
        private static InstitutionElements defaultInstance = ((InstitutionElements)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new InstitutionElements())));
        
        public static InstitutionElements Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Name")]
        public string InstitutionName {
            get {
                return ((string)(this["InstitutionName"]));
            }
            set {
                this["InstitutionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Email")]
        public string InstitutionEmail {
            get {
                return ((string)(this["InstitutionEmail"]));
            }
            set {
                this["InstitutionEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Phone")]
        public string InstitutionPhone {
            get {
                return ((string)(this["InstitutionPhone"]));
            }
            set {
                this["InstitutionPhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ShortName")]
        public string InstitutionShortName {
            get {
                return ((string)(this["InstitutionShortName"]));
            }
            set {
                this["InstitutionShortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DefaultBranchName")]
        public string InstitutionDefaultBranchName {
            get {
                return ((string)(this["InstitutionDefaultBranchName"]));
            }
            set {
                this["InstitutionDefaultBranchName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DefaultRegionName")]
        public string InstitutionDefaultRegionName {
            get {
                return ((string)(this["InstitutionDefaultRegionName"]));
            }
            set {
                this["InstitutionDefaultRegionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Address")]
        public string InstitutionAddress {
            get {
                return ((string)(this["InstitutionAddress"]));
            }
            set {
                this["InstitutionAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Slogan")]
        public string InstitutionSlogan {
            get {
                return ((string)(this["InstitutionSlogan"]));
            }
            set {
                this["InstitutionSlogan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FirstName")]
        public string InstituteAdminFirstName {
            get {
                return ((string)(this["InstituteAdminFirstName"]));
            }
            set {
                this["InstituteAdminFirstName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#LastName")]
        public string InstituteAdminLastName {
            get {
                return ((string)(this["InstituteAdminLastName"]));
            }
            set {
                this["InstituteAdminLastName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ContactPhone")]
        public string InstituteAdminContactPhone {
            get {
                return ((string)(this["InstituteAdminContactPhone"]));
            }
            set {
                this["InstituteAdminContactPhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ContactEmail")]
        public string InstituteAdminContactEmail {
            get {
                return ((string)(this["InstituteAdminContactEmail"]));
            }
            set {
                this["InstituteAdminContactEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Save")]
        public string InstitutionSave {
            get {
                return ((string)(this["InstitutionSave"]));
            }
            set {
                this["InstitutionSave"] = value;
            }
        }
    }
}
