//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZoneTestProjects.Functional.Reports.Settings.Interface.Workspace {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class WorkspaceElement : global::System.Configuration.ApplicationSettingsBase {
        
        private static WorkspaceElement defaultInstance = ((WorkspaceElement)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WorkspaceElement())));
        
        public static WorkspaceElement Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#left-panel > nav > ul > li.open > ul > li.open > ul > li:nth-child(3) > a")]
        public string WFTreated {
            get {
                return ((string)(this["WFTreated"]));
            }
            set {
                this["WFTreated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#left-panel > nav > ul > li.open > ul > li.open > ul > li:nth-child(2) > a")]
        public string WFSent {
            get {
                return ((string)(this["WFSent"]));
            }
            set {
                this["WFSent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#left-panel > nav > ul > li.open > ul > li.open > ul > li:nth-child(1) > a")]
        public string WFInbox {
            get {
                return ((string)(this["WFInbox"]));
            }
            set {
                this["WFInbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#left-panel > nav > ul > li.open > ul > li:nth-child(1) > a")]
        public string WFolder {
            get {
                return ((string)(this["WFolder"]));
            }
            set {
                this["WFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#left-panel > nav > ul > li:nth-child(1) > a")]
        public string Workspace {
            get {
                return ((string)(this["Workspace"]));
            }
            set {
                this["Workspace"] = value;
            }
        }
    }
}
