//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZoneTestProjects.Functional.Reports.Settings.Interface.Workspace {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class WorkspaceValidation : global::System.Configuration.ApplicationSettingsBase {
        
        private static WorkspaceValidation defaultInstance = ((WorkspaceValidation)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WorkspaceValidation())));
        
        public static WorkspaceValidation Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#form1 > div.inbox-nav-bar.no-content-padding > h1 > span > a")]
        public string WFTopIconsDropdown {
            get {
                return ((string)(this["WFTopIconsDropdown"]));
            }
            set {
                this["WFTopIconsDropdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#form1 > div.inbox-nav-bar.no-content-padding > div.inbox-checkbox-triggered > di" +
            "v > a.inbox-load.btn.btn-default > strong > i")]
        public string WFTopIconBack {
            get {
                return ((string)(this["WFTopIconBack"]));
            }
            set {
                this["WFTopIconBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#form1 > div.inbox-nav-bar.no-content-padding > div.inbox-checkbox-triggered > di" +
            "v > a:nth-child(2) > strong > i")]
        public string WFTopIconFolder {
            get {
                return ((string)(this["WFTopIconFolder"]));
            }
            set {
                this["WFTopIconFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#form1 > div.inbox-nav-bar.no-content-padding > div.inbox-checkbox-triggered > di" +
            "v > a.deletebutton.btn.btn-default > strong > i")]
        public string WFTopIconDelete {
            get {
                return ((string)(this["WFTopIconDelete"]));
            }
            set {
                this["WFTopIconDelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#form1 > div.inbox-nav-bar.no-content-padding > div.btn-group.pull-right.inbox-pa" +
            "ging > a:nth-child(1)")]
        public string WFTopIconBackward {
            get {
                return ((string)(this["WFTopIconBackward"]));
            }
            set {
                this["WFTopIconBackward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#form1 > div.inbox-nav-bar.no-content-padding > div.btn-group.pull-right.inbox-pa" +
            "ging > a:nth-child(2)")]
        public string WFTopIconForward {
            get {
                return ((string)(this["WFTopIconForward"]));
            }
            set {
                this["WFTopIconForward"] = value;
            }
        }
    }
}
