//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZoneTestProjects.Functional.Reports.Settings.Interface.SystemAdmin.Groups {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class GroupsElements : global::System.Configuration.ApplicationSettingsBase {
        
        private static GroupsElements defaultInstance = ((GroupsElements)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GroupsElements())));
        
        public static GroupsElements Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#left-panel > nav > ul > li.open > ul > li:nth-child(2) > a")]
        public string Groups {
            get {
                return ((string)(this["Groups"]));
            }
            set {
                this["Groups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#mainMenuNav > li > a")]
        public string GroupAdd {
            get {
                return ((string)(this["GroupAdd"]));
            }
            set {
                this["GroupAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Name")]
        public string GroupName {
            get {
                return ((string)(this["GroupName"]));
            }
            set {
                this["GroupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Code")]
        public string GroupCode {
            get {
                return ((string)(this["GroupCode"]));
            }
            set {
                this["GroupCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Search")]
        public string GroupSearch {
            get {
                return ((string)(this["GroupSearch"]));
            }
            set {
                this["GroupSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reset")]
        public string GroupReset {
            get {
                return ((string)(this["GroupReset"]));
            }
            set {
                this["GroupReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Save")]
        public string GroupSave {
            get {
                return ((string)(this["GroupSave"]));
            }
            set {
                this["GroupSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GrantSystemAdminFuncs")]
        public string GroupSysAdminFunc {
            get {
                return ((string)(this["GroupSysAdminFunc"]));
            }
            set {
                this["GroupSysAdminFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#s2id_TheFunctions > ul")]
        public string GroupUserFunctions {
            get {
                return ((string)(this["GroupUserFunctions"]));
            }
            set {
                this["GroupUserFunctions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GrantServiceBuilderFuncs")]
        public string GroupDevFunction {
            get {
                return ((string)(this["GroupDevFunction"]));
            }
            set {
                this["GroupDevFunction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#UserRoleAddUI > footer")]
        public string GroupAddFooter {
            get {
                return ((string)(this["GroupAddFooter"]));
            }
            set {
                this["GroupAddFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#UserRoles_wrapper > div.dt-toolbar-footer")]
        public string GroupFooter {
            get {
                return ((string)(this["GroupFooter"]));
            }
            set {
                this["GroupFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Description")]
        public string GroupDescription {
            get {
                return ((string)(this["GroupDescription"]));
            }
            set {
                this["GroupDescription"] = value;
            }
        }
    }
}
