//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZoneTestProjects.Functional.Reports.Settings.Interface.SystemAdmin {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SystemAdmins : global::System.Configuration.ApplicationSettingsBase {
        
        private static SystemAdmins defaultInstance = ((SystemAdmins)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SystemAdmins())));
        
        public static SystemAdmins Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#left-panel > nav > ul > li:nth-child(3) > a")]
        public string SystemAdmin {
            get {
                return ((string)(this["SystemAdmin"]));
            }
            set {
                this["SystemAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#left-panel > nav > ul > li.open > ul > li:nth-child(1) > a")]
        public string Users {
            get {
                return ((string)(this["Users"]));
            }
            set {
                this["Users"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ChangePasswordUI > footer")]
        public string LoginPageLoadValidate {
            get {
                return ((string)(this["LoginPageLoadValidate"]));
            }
            set {
                this["LoginPageLoadValidate"] = value;
            }
        }
    }
}
