//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZoneTestProjects.Functional.Reports.Settings.Login {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class LoginValidation : global::System.Configuration.ApplicationSettingsBase {
        
        private static LoginValidation defaultInstance = ((LoginValidation)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LoginValidation())));
        
        public static LoginValidation Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#content > div > div.col-xs-12.col-sm-12.col-md-7.col-lg-8.hidden-xs.hidden-sm > " +
            "div.hero > img")]
        public string ImageValidatePageLoad {
            get {
                return ((string)(this["ImageValidatePageLoad"]));
            }
            set {
                this["ImageValidatePageLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ChangePasswordUI > footer")]
        public string LoginSuccessfulValidate {
            get {
                return ((string)(this["LoginSuccessfulValidate"]));
            }
            set {
                this["LoginSuccessfulValidate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Msg1")]
        public string FailedLoginPanel {
            get {
                return ((string)(this["FailedLoginPanel"]));
            }
            set {
                this["FailedLoginPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ChangePasswordUI > div > header > h2")]
        public string ChangePassword {
            get {
                return ((string)(this["ChangePassword"]));
            }
            set {
                this["ChangePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("body > div.page-footer > div")]
        public string DefaultFooter {
            get {
                return ((string)(this["DefaultFooter"]));
            }
            set {
                this["DefaultFooter"] = value;
            }
        }
    }
}
