//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZoneTestProjects.Functional.Reports.Settings.Login {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class LoginElements : global::System.Configuration.ApplicationSettingsBase {
        
        private static LoginElements defaultInstance = ((LoginElements)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LoginElements())));
        
        public static LoginElements Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165.233.246.31/DejaVuMobile/TradeportLogin.aspx")]
        public string DejaVuURL {
            get {
                return ((string)(this["DejaVuURL"]));
            }
            set {
                this["DejaVuURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("username")]
        public string DejaVuUsernameTextbox {
            get {
                return ((string)(this["DejaVuUsernameTextbox"]));
            }
            set {
                this["DejaVuUsernameTextbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string DejaVuPasswordTextbox {
            get {
                return ((string)(this["DejaVuPasswordTextbox"]));
            }
            set {
                this["DejaVuPasswordTextbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("institutionCode")]
        public string DejaVuInstitutionCodeTextbox {
            get {
                return ((string)(this["DejaVuInstitutionCodeTextbox"]));
            }
            set {
                this["DejaVuInstitutionCodeTextbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("btnSigin")]
        public string DejaVuLoginButton {
            get {
                return ((string)(this["DejaVuLoginButton"]));
            }
            set {
                this["DejaVuLoginButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:4477/wd/hub")]
        public string SeleniumHubURL {
            get {
                return ((string)(this["SeleniumHubURL"]));
            }
            set {
                this["SeleniumHubURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#bot1-Msg1")]
        public string DejavuFalseLoginOKButton {
            get {
                return ((string)(this["DejavuFalseLoginOKButton"]));
            }
            set {
                this["DejavuFalseLoginOKButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Msg1 > div")]
        public string DejavuFalseLoginForm {
            get {
                return ((string)(this["DejavuFalseLoginForm"]));
            }
            set {
                this["DejavuFalseLoginForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#bot1-Msg1")]
        public string FailedLoginButton {
            get {
                return ((string)(this["FailedLoginButton"]));
            }
            set {
                this["FailedLoginButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginSuccessful {
            get {
                return ((string)(this["LoginSuccessful"]));
            }
            set {
                this["LoginSuccessful"] = value;
            }
        }
    }
}
