//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZoneTestProjects.Functional.Reports.Settings.Interface.ServiceBuilder.Entity {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class EntityElements : global::System.Configuration.ApplicationSettingsBase {
        
        private static EntityElements defaultInstance = ((EntityElements)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EntityElements())));
        
        public static EntityElements Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Name")]
        public string EntityName {
            get {
                return ((string)(this["EntityName"]));
            }
            set {
                this["EntityName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Description")]
        public string EntityDescription {
            get {
                return ((string)(this["EntityDescription"]));
            }
            set {
                this["EntityDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DisplayName")]
        public string EntityDisplayName {
            get {
                return ((string)(this["EntityDisplayName"]));
            }
            set {
                this["EntityDisplayName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#MainEntityAddUI > fieldset:nth-child(2) > div:nth-child(1) > section:nth-child(2" +
            ") > label.toggle > i")]
        public string EntityStatus {
            get {
                return ((string)(this["EntityStatus"]));
            }
            set {
                this["EntityStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#MainEntityAddUI > fieldset:nth-child(2) > div:nth-child(3) > section > label.tog" +
            "gle > i")]
        public string EntityGlobal {
            get {
                return ((string)(this["EntityGlobal"]));
            }
            set {
                this["EntityGlobal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#MainEntityAddUI > fieldset:nth-child(4) > section:nth-child(1) > label.toggle > " +
            "i")]
        public string EntityNewCategory {
            get {
                return ((string)(this["EntityNewCategory"]));
            }
            set {
                this["EntityNewCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#select2-chosen-34")]
        public string EntityCategory {
            get {
                return ((string)(this["EntityCategory"]));
            }
            set {
                this["EntityCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#MainEntityAddUI > button")]
        public string EntityAddProp {
            get {
                return ((string)(this["EntityAddProp"]));
            }
            set {
                this["EntityAddProp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Save")]
        public string EntitySave {
            get {
                return ((string)(this["EntitySave"]));
            }
            set {
                this["EntitySave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Parameters_1_Name")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
