//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZoneTestProjects.Functional.Reports.Settings.Interface.ServiceBuilder {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ServiceBuilderElements : global::System.Configuration.ApplicationSettingsBase {
        
        private static ServiceBuilderElements defaultInstance = ((ServiceBuilderElements)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ServiceBuilderElements())));
        
        public static ServiceBuilderElements Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#left-panel > nav > ul > li:nth-child(5) > a > span")]
        public string ServiceBuilder {
            get {
                return ((string)(this["ServiceBuilder"]));
            }
            set {
                this["ServiceBuilder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#select2-chosen-2")]
        public string SelectAService {
            get {
                return ((string)(this["SelectAService"]));
            }
            set {
                this["SelectAService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("body > script:nth-child(34)")]
        public string DefaultClick {
            get {
                return ((string)(this["DefaultClick"]));
            }
            set {
                this["DefaultClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#mainMenuNav > li > a")]
        public string CreateEntity {
            get {
                return ((string)(this["CreateEntity"]));
            }
            set {
                this["CreateEntity"] = value;
            }
        }
    }
}
